### ISSUE TITLE
All geometry components should take materials as inputs

### ISSUE THREAD

**Issue by bhowes-tt** [va3c/GHvA3C#14]
As I mentioned in #12, I've been using these components on a real project and have found one early design decision to be especially unfortunate ... during the hackathon we thought it made sense to combine meshes and materials in the collector component using typical grasshopper iteration to do the matching.  

This is inconvenient when you have lists or trees of meshes where different items (or entire collections) want to be assigned different materials.  It would be better if the material was an input to the geometry components.  This is a closer fit to how three.js actually works: to make a geometry object, you need a mesh and a material.  Objects are made of meshes and materials, and scenes are made of objects.

Rebuild all components.  Make geometry components take materials as inputs, and make the collector component more general - it should just accept a data tree of geometry objects, and each one should already be assigned a material.  Create grasshopper parameters to wrap around vA3C specific types like material, mesh, line, curve, etc.

**Comment by anagpuyol** [comment]
I just did this :fast_forward:
