### ISSUE TITLE
License

### ISSUE THREAD

**Issue by chrzyki** [va3c/GHvA3C#18]
@bhowes-tt, thank you very much for providing such an awesome library with GHvA3C! I've been wondering about the license of the project: https://va3c.github.io/ mentions the MIT License at the bottom - is this the license that holds for all the projects in va3c?

**Comment by bhowes-tt** [comment]
Hey @chrzyki - Yes, safe to assume all projects within the va3c github organization are licensed under MIT license found here:

https://github.com/vA3C/va3c.github.io/blob/master/LICENSE

**Comment by chrzyki** [comment]
Awesome, thank you!
